# -*- coding: utf-8 -*-
"""trabalho_topicos_avancados_gabriellycristine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F6zzINpqu672miZkikJbqmT4SeLZ4rig
"""

import pandas as pd
import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import plotly.express as px

# Carregar os dados
df = pd.read_excel("conceito_enade_2023.xlsx", sheet_name="PLANILHA_ENADE")

# Corrigir nomes de colunas (remover espaços extras)
df.columns = df.columns.str.strip()

# Inicializar o app
app = dash.Dash(__name__)
app.title = "Dashboard ENADE 2023"

# Layout
app.layout = html.Div([
    html.H1("Indicadores de Qualidade da Educação Superior - ENADE 2023 - Gabrielly Cristine", style={'textAlign': 'center'}),

    html.Div([
        html.Label("Filtrar por UF:"),
        dcc.Dropdown(
            options=[{"label": uf, "value": uf} for uf in sorted(df["Sigla da UF**"].dropna().unique())],
            id="uf-filter",
            placeholder="Selecione uma UF",
            style={"width": "40%"}
        ),
    ], style={"padding": "20px"}),

    dcc.Graph(id="bar-conceito"),
    dcc.Graph(id="scatter-notas"),
])

# Callback
@app.callback(
    [Output("bar-conceito", "figure"),
     Output("scatter-notas", "figure")],
    [Input("uf-filter", "value")]
)
def update_graphs(selected_uf):
    filtered_df = df if not selected_uf else df[df["Sigla da UF**"] == selected_uf]

    bar_data = filtered_df.groupby("Área de Avaliação")["Conceito Enade (Contínuo)"].mean().reset_index()
    bar_fig = px.bar(
        bar_data,
        x="Conceito Enade (Contínuo)",
        y="Área de Avaliação",
        orientation="h",
        title="Média do Conceito Enade por Curso",
        height=600
    )

    scatter_fig = px.scatter(
        filtered_df,
        x="Nota Padronizada - FG",
        y="Nota Padronizada - CE",
        color="Conceito Enade (Faixa)",
        hover_data=["Nome da IES*", "Área de Avaliação"],
        title="Nota Padronizada FG x CE",
    )

    return bar_fig, scatter_fig

# Rodar o app
if __name__ == "__main__":
    app.run(debug=True)



pip install pandas dash plotly openpyxl
